---
definitions:
  TEXT_T: &TEXT_T
    name: data.consensus_text
    type: text
  DROP_T: &DROP_T
    name: data.value
    type: dropdown
  STR: &STR !!python/name:builtins.str ''
  INT64: &INT64 !!python/object:pandas.core.arrays.integer.Int64Dtype {}

development_workflows:
  18109:
    name: admission number
    nptype: *INT64
    ztype: *TEXT_T
  18110:
    name: date admitted
    nptype: *STR
    ztype: *TEXT_T
  18111:
    name: name
    nptype: *STR
    ztype: *TEXT_T
  18112:
    major: 5
    minor: 8
    name: rank/rating
    nptype: *STR
    ztype: *DROP_T
  18113:
    name: age
    nptype: *INT64
    ztype: *TEXT_T
  18114:
    name: place of birth
    nptype: *STR
    ztype: *TEXT_T
  18115:
    name: port sailed out of
    nptype: *STR
    ztype: *TEXT_T
  18116:
    name: years at sea
    nptype: *INT64
    ztype: *TEXT_T
  18117:
    name: last ship
    nptype: *STR
    ztype: *TEXT_T
  18118:
    name: admission circumstances
    nptype: *STR
    ztype: *TEXT_T
  18119:
    name: date discharged
    nptype: *STR
    ztype: *TEXT_T
  18120:
    major: 1
    minor: 1
    name: how disposed
    nptype: *STR
    ztype: *DROP_T
  18121:
    name: days victualled/in hospital
    nptype: *INT64
    ztype: *TEXT_T
