---
definitions:
  TEXT_T: &TEXT_T
    name: data.consensus_text
    type: text
  DROP_T: &DROP_T
    name: data.value
    type: dropdown
  STR: &STR !!python/name:builtins.str ''
  INT64: &INT64 !!python/name:pandas.core.arrays.integer.Int64Dtype
  DATE: &DATE !!python/name:datetime.date

subjects:
  export: 'hms-nhs-the-nautical-health-service-subjects.csv'
  supplements:
    #Subject ids which have classifications but do not exist in the subjects file
    #All of these values inferred by looking at neighbouring subjects
    #
    #The final known page in volume 20 is p. 157, so there is no "following" page for the top 3 subjects here
    #They could therefore be from volume 21, but as the first known page in vol. 21 is p. 1, I have placed
    #them at the end of vol. 20.
    60262144:
      volume: 20
      page: 158
      location: supplement
    60262145:
      volume: 20
      page: 159
      location: supplement
    60262146:
      volume: 20
      page: 160
      location: supplement
    44585952:
      volume: 23
      page: 204
      location: supplement
    44586138:
      volume: 24
      page: 136
      location: supplement
    44586661:
      volume: 26
      page: 57
      location: supplement
    44586737:
      volume: 26
      page: 131
      location: supplement
    44586811:
      volume: 26
      page: 202
      location: supplement
    44586878:
      volume: 26
      page: 268
      location: supplement
    44661091:
      volume: 28
      page: 57
      location: supplement
    44661092:
      volume: 28
      page: 58
      location: supplement

development_workflows:
  18109:
    name: admission number
    nptype: *INT64
    ztype: *TEXT_T
  18110:
    name: date admitted
    nptype: *DATE
    ztype: *TEXT_T
  18111:
    name: name
    nptype: *STR
    ztype: *TEXT_T
  18112:
    version: "5.8"
    name: rank/rating
    nptype: *STR
    ztype: *DROP_T
  18113:
    name: age
    nptype: *INT64
    ztype: *TEXT_T
  18114:
    name: place of birth
    nptype: *STR
    ztype: *TEXT_T
  18115:
    name: port sailed out of
    nptype: *STR
    ztype: *TEXT_T
  18116:
    name: years at sea
    nptype: *INT64
    ztype: *TEXT_T
  18117:
    name: last ship
    nptype: *STR
    ztype: *TEXT_T
  18118:
    name: admission circumstances
    nptype: *STR
    ztype: *TEXT_T
  18119:
    name: date discharged
    nptype: *DATE
    ztype: *TEXT_T
  18120:
    version: "1.1"
    name: how disposed
    nptype: *STR
    ztype: *DROP_T
  18121:
    name: days victualled/in hospital
    nptype: *INT64
    ztype: *TEXT_T

#Here we know what the release versions are, but we also use volume limiting because v3.1 of the admissions
#workflow was used for a few phase 2 classifications.
phase1:
  first_volume:  1
  final_volume: 18
  workflows:
    18611:
      version: "3.1"
      name: admission number
      export: 1-admission-number-classifications.csv
      nptype: *INT64
      ztype: *TEXT_T
    18612:
      version:
        - "3.1"
        - "4.1"
      name: date of entry
      export: 2-date-of-entry-classifications.csv
      nptype: *DATE
      ztype: *TEXT_T
    18613:
      version: "3.1"
      name: name
      export: 3-name-classifications.csv
      nptype: *STR
      ztype: *TEXT_T
    18614:
      version: "3.1"
      name: quality
      export: quality-dd-classifications.csv
      nptype: *STR
      ztype: *DROP_T
    18616:
      version: "3.1"
      name: age
      export: 5-age-classifications.csv
      nptype: *INT64
      ztype: *TEXT_T
    18617:
      version: "3.1"
      name: place of birth
      export: 7-place-of-birth-nationality-classifications.csv
      nptype: *STR
      ztype: *TEXT_T
    18618:
      version: "3.1"
      name: port sailed out of
      export: 10-where-from-classifications.csv
      nptype: *STR
      ztype: *TEXT_T
    18619:
      version: "3.1"
      name: years at sea
      export: years-at-sea-classifications.csv
      nptype: *INT64
      ztype: *TEXT_T
    18621:
      version: "3.1"
      name: last services
      export: 8-ship-ship-or-place-of-employment-last-ship-classifications.csv
      nptype: *STR
      ztype: *TEXT_T
    18622:
      version: "3.1"
      name: under what circumstances admitted (or nature of complaint)
      export: 11-nature-of-complaint-classifications.csv
      nptype: *STR
      ztype: *TEXT_T
    18623:
      version: "3.1"
      name: date of discharge
      export: 12-date-of-discharge-classifications.csv
      nptype: *DATE
      ztype: *TEXT_T
    18624:
      version:
        - "3.1"
        - "6.4"
      name: how disposed of
      export: how-disposed-of-dd-classifications.csv
      nptype: *STR
      ztype: *DROP_T
    18625:
      version: "3.1"
      name: number of days victualled
      export: 14-number-of-days-in-hospital-classifications.csv
      nptype: *INT64
      ztype: *TEXT_T

#Here we do not attempt to use version limiting at all, but rather pull in all versions and rely upon volume limiting
#TOOD: Are we pulling in any versions that were never part of a live workflow? (they might still have test classifications)
phase2:
  first_volume: 19
  final_volume: 34
  workflows:
    18611:
      name: admission number
      export: 1-admission-number-classifications.csv
      nptype: *INT64
      ztype: *TEXT_T
    18612:
      name: date of entry
      export: 2-date-of-entry-classifications.csv
      nptype: *DATE
      ztype: *TEXT_T
    18613:
      name: name
      export: 3-name-classifications.csv
      nptype: *STR
      ztype: *TEXT_T
    18454:
      name: quality
      export: 4-quality-classifications.csv
      nptype: *STR
      ztype: *TEXT_T
    18616:
      name: age
      export: 5-age-classifications.csv
      nptype: *INT64
      ztype: *TEXT_T
    18344:
      name: creed
      export: 6-creed-classifications.csv
      nptype: *STR
      ztype: *TEXT_T
    18617:
      name: place of birth/nationality
      export: 7-place-of-birth-nationality-classifications.csv
      nptype: *STR
      ztype: *TEXT_T
    18621:
      name: ship/ship or place of employment/last ship
      export: 8-ship-ship-or-place-of-employment-last-ship-classifications.csv
      nptype: *STR
      ztype: *TEXT_T
    18347:
      name: of what port/port of registration
      export: 9-of-what-port-port-of-registration-classifications.csv
      nptype: *STR
      ztype: *TEXT_T
    18618:
      name: where from
      export: 10-where-from-classifications.csv
      nptype: *STR
      ztype: *TEXT_T
    18622:
      name: nature of complaint
      export: 11-nature-of-complaint-classifications.csv
      nptype: *STR
      ztype: *TEXT_T
    18623:
      name: date of discharge
      export: 12-date-of-discharge-classifications.csv
      nptype: *DATE
      ztype: *TEXT_T
    20285:
      name: how disposed of
      export: 13-how-disposed-of-classifications.csv
      nptype: *STR
      ztype: *TEXT_T
    18625:
      name: number of days in hospital
      export: 14-number-of-days-in-hospital-classifications.csv
      nptype: *INT64
      ztype: *TEXT_T
