---
definitions:
  TEXT_T: &TEXT_T
    name: data.consensus_text
    type: text
  DROP_T: &DROP_T
    name: data.value
    type: dropdown
  STR: &STR !!python/name:builtins.str ''
  INT64: &INT64 !!python/name:pandas.core.arrays.integer.Int64Dtype
  DATE: &DATE !!python/name:datetime.date

export: 'hms-nhs-the-nautical-health-service-workflows.csv'

subjects:
  export: 'hms-nhs-the-nautical-health-service-subjects.csv'
  supplements:
    #Subject ids which have classifications but do not exist in the subjects file
    #All of these values inferred by looking at neighbouring subjects
    #
    #The final known page in volume 20 is p. 157, so there is no "following" page for the top 3 subjects here
    #They could therefore be from volume 21, but as the first known page in vol. 21 is p. 1, I have placed
    #them at the end of vol. 20.
    #
    #Page 1 of volume 2 could almost equally well be a late page of volume 1. I've chosen to make it page 1 of
    #volume 2 because (a) page 1 is obviously missing, while there is no guarantee that there is a page 81 of vol 1
    #and (b) there are a few missing subject ids here, and 44290143 happens to be one lower than the subject id for
    #vol 2 p. 2
    44290143:
      volume: 2
      page: 1
      location: supplement
    60262183:
      volume: 20
      page: 54
      location: supplement
    60262144:
      volume: 20
      page: 158
      location: supplement
    60262145:
      volume: 20
      page: 159
      location: supplement
    60262146:
      volume: 20
      page: 160
      location: supplement
    44585952:
      volume: 23
      page: 204
      location: supplement
    44586138:
      volume: 24
      page: 136
      location: supplement
    44586661:
      volume: 26
      page: 57
      location: supplement
    44586737:
      volume: 26
      page: 131
      location: supplement
    44586811:
      volume: 26
      page: 202
      location: supplement
    44586878:
      volume: 26
      page: 268
      location: supplement
    44661091:
      volume: 28
      page: 57
      location: supplement
    44661092:
      volume: 28
      page: 58
      location: supplement

development_workflows:
  18109:
    name: admission number
    nptype: *INT64
    ztype: *TEXT_T
  18110:
    name: date admitted
    nptype: *DATE
    ztype: *TEXT_T
  18111:
    name: name
    nptype: *STR
    ztype: *TEXT_T
  18112:
    version: "5.8"
    name: rank/rating
    nptype: *STR
    ztype: *DROP_T
  18113:
    name: age
    nptype: *INT64
    ztype: *TEXT_T
  18114:
    name: place of birth
    nptype: *STR
    ztype: *TEXT_T
  18115:
    name: port sailed out of
    nptype: *STR
    ztype: *TEXT_T
  18116:
    name: years at sea
    nptype: *INT64
    ztype: *TEXT_T
  18117:
    name: last ship
    nptype: *STR
    ztype: *TEXT_T
  18118:
    name: admission circumstances
    nptype: *STR
    ztype: *TEXT_T
  18119:
    name: date discharged
    nptype: *DATE
    ztype: *TEXT_T
  18120:
    version: "1.1"
    name: how disposed
    nptype: *STR
    ztype: *DROP_T
  18121:
    name: days victualled/in hospital
    nptype: *INT64
    ztype: *TEXT_T

#Here we know what the release versions are, but we also use volume limiting because v3.1 of the admissions
#workflow was used for a few phase 2 classifications.
phase1:
  first_volume:  1
  final_volume: 18
  workflows:
    18611:
      version: "3.1"
      name: admission number
      export: 1-admission-number-classifications.csv
      nptype: *INT64
      ztype: *TEXT_T
    18612:
      version:
        - "3.1"
        - "4.1"
      name: date of entry
      export: 2-date-of-entry-classifications.csv
      nptype: *DATE
      ztype: *TEXT_T
    18613:
      version: "3.1"
      name: name
      export: 3-name-classifications.csv
      nptype: *STR
      ztype: *TEXT_T
    18614:
      version: "3.1"
      name: quality
      export: quality-dd-classifications.csv
      nptype: *STR
      ztype: *DROP_T
    18616:
      version: "3.1"
      name: age
      export: 5-age-classifications.csv
      nptype: *INT64
      ztype: *TEXT_T
    18617:
      version: "3.1"
      name: place of birth
      export: 7-place-of-birth-nationality-classifications.csv
      nptype: *STR
      ztype: *TEXT_T
    18618:
      version: "3.1"
      name: port sailed out of
      export: 10-where-from-classifications.csv
      nptype: *STR
      ztype: *TEXT_T
    18619:
      version: "3.1"
      name: years at sea
      export: years-at-sea-classifications.csv
      nptype: *INT64
      ztype: *TEXT_T
    18621:
      version: "3.1"
      name: last services
      export: 8-ship-ship-or-place-of-employment-last-ship-classifications.csv
      nptype: *STR
      ztype: *TEXT_T
    18622:
      version: "3.1"
      name: under what circumstances admitted (or nature of complaint)
      export: 11-nature-of-complaint-classifications.csv
      nptype: *STR
      ztype: *TEXT_T
    18623:
      version: "3.1"
      name: date of discharge
      export: 12-date-of-discharge-classifications.csv
      nptype: *DATE
      ztype: *TEXT_T
    18624:
      version:
        - "3.1"
        - "6.4"
      name: how disposed of
      export: how-disposed-of-dd-classifications.csv
      nptype: *STR
      ztype: *DROP_T
    18625:
      version: "3.1"
      name: number of days victualled
      export: 14-number-of-days-in-hospital-classifications.csv
      nptype: *INT64
      ztype: *TEXT_T

#Here we do not attempt to use version limiting at all, but rather pull in all versions and rely upon volume limiting
#TOOD: Are we pulling in any versions that were never part of a live workflow? (they might still have test classifications). What I have done here is to explicitly list all versions where the task slots have increased over phase1 (see config_file_comparisons_phase2.ods). The one exception is admission number (18611), where 3.1 is included because it has some classifications from vol 19.
#Note that there are some cases where there are still different numbers of task slots in the extractions. I have set extract_diff_ok for these cases. I think that the consquence is just that workflows with versions with different numbers of task slots will not always produce the same number of tasks -- presumably similar to what would happen if a volunteer completed a classification early. As an added sanity check, just in case the reduction phase was using any information in the extraction configs, I re-ran it with all extraction configs removed. This did not cause any change in output.
phase2:
  first_volume: 19
  final_volume: 34
  workflows:
    18611:
      version:
        - "3.1" #There are a few phase 2 classifications in 3.1
        - "58.65"
        - "58.132"
      extract_diff_ok: True
      name: admission number
      export: 1-admission-number-classifications.csv
      nptype: *INT64
      ztype: *TEXT_T
    18612:
      version:
        - "47.30" #only 1 case
        - "47.47"
      name: date of entry
      export: 2-date-of-entry-classifications.csv
      nptype: *DATE
      ztype: *TEXT_T
    18613:
      version:
        - "23.19"
        - "23.34"
      name: name
      export: 3-name-classifications.csv
      nptype: *STR
      ztype: *TEXT_T
    18454:
      version:
        - "19.70"
        - "21.70"
      name: quality
      export: 4-quality-classifications.csv
      nptype: *STR
      ztype: *TEXT_T
    18616:
      version:
        - "25.36"
        - "25.51"
      name: age
      export: 5-age-classifications.csv
      nptype: *INT64
      ztype: *TEXT_T
    18344:
      version:
        - "26.117"
        - "28.117"
      name: creed
      export: 6-creed-classifications.csv
      nptype: *STR
      ztype: *TEXT_T
    18617:
      version: "22.46"
      name: place of birth/nationality
      export: 7-place-of-birth-nationality-classifications.csv
      nptype: *STR
      ztype: *TEXT_T
    18621:
      version: "22.49"
      name: ship/ship or place of employment/last ship
      export: 8-ship-ship-or-place-of-employment-last-ship-classifications.csv
      nptype: *STR
      ztype: *TEXT_T
    18347:
      version:
        - "24.49"
        - "26.49"
      name: of what port/port of registration
      export: 9-of-what-port-port-of-registration-classifications.csv
      nptype: *STR
      ztype: *TEXT_T
    18618:
      version:
        - "21.44"
        - "21.45"
      name: where from
      export: 10-where-from-classifications.csv
      nptype: *STR
      ztype: *TEXT_T
    18622:
      version:
        - "21.55"
        - "21.68"
      name: nature of complaint
      export: 11-nature-of-complaint-classifications.csv
      nptype: *STR
      ztype: *TEXT_T
    18623:
      version:
        - "29.41"
        - "33.43" #this 1 has an extra task slot over the usual 8
      extract_diff_ok: True
      name: date of discharge
      export: 12-date-of-discharge-classifications.csv
      nptype: *DATE
      ztype: *TEXT_T
    20285:
      version:
        - "22.79" #this 1 has an extra task slot over the usual 8
        - "23.82"
      extract_diff_ok: True
      name: how disposed of
      export: 13-how-disposed-of-classifications.csv
      nptype: *STR
      ztype: *TEXT_T
    18625:
      version: "30.47"
      name: number of days in hospital
      export: 14-number-of-days-in-hospital-classifications.csv
      nptype: *INT64
      ztype: *TEXT_T
